version : '3'

services:
  mysql:
    container_name: mysql5.7.17
    image: mysql:5.7.17
    volumes:
     - ./data:/var/lib/mysql
     - ./conf.d:/etc/mysql/conf.d
     - ./init:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_USER=test
     - MYSQL_ROOT_PASSWORD=root1234
     - MYSQL_PASSWORD=test1234
    ports:
     - 3307:3306
